### ISSUE TITLE
Data reader typing

### ISSUE THREAD

**Issue by memark** [andreiduca/use-async-resource#3]
Great work with this package! It's really helpful! :star:

The readme states

> ### Type inference for the data reader
>
>The data reader will return exactly the type the original api function returns as a Promise.
>
>```tsx
>const fetchUser = (userId: number): Promise<UserType> => fetch('...');
>
>const [userReader] = useAsyncResource(fetchUser, 1);
>```
>
>`userReader` is inferred as `() => UserType`, meaning a `function` that returns a `UserType` object.

In my experience, that is not entirely correct. Consider the following dummy code:

```tsx
interface UserType {}

const fetchUser = (userId: number): Promise<UserType> => null as any;
const [userReader] = useAsyncResource(fetchUser, 1);
```

`userReader` is then inferred to be of type `DataOrModifiedFn<UserType>`, not `() => UserType`.

If this change is intentional, the readme should be updated.

`userReader` can still be cast to the mentioned type though:

```tsx
const somePropsProperty: () => UserType = userReader;
```
which I would probably want to do when defining props interfaces for my components as I'd like to avoid exposing (the somewhat strange looking) `DataOrModifiedFn` in them. Would you agree?

**Comment by andreiduca** [comment]
Hi @memark.

`DataOrModifiedFn<UserType>` is a "superset" of `() => UserType`, so you can safely use the latter in your components props definitions. The only difference is that `DataOrModifiedFn<UserType>` can also [accept a modifier function](https://github.com/andreiduca/use-async-resource#data-modifiers):

```ts
(modifier: (r: UserType) => M) => M
```

Accepting both is even weirder to write in your props:

```ts
(() => UserType) & ((modifier: (r: UserType) => M) => M)
```

So, when you know you will need a modifier for your data reader, `DataOrModifiedFn<UserType>` is a cleaner way to write it. But in practice, most of the time you won't need it, so `() => UserType` will just work.

**Comment by memark** [comment]
Thanks @andreiduca, that's a good explanation!

Perhaps so good as to put it in the docs? IMHO they are still a bit misleading.
