### ISSUE TITLE
How to add/remove an item to the `DataFn` that is temporarily in draft (not sync with server)

### ISSUE THREAD

**Issue by ace-han** [andreiduca/use-async-resource#38]
Hello there, we would like to edit the data that fetching back from somewhere in real world.

Is there any demo that shows how to add/remove an item to the list in draft (not sync with remote server)?

Take grafana for example, a dashboard contains many panels (fetched from server). We can insert a new panel or remove panels, and by clicking the save button the changes are sync with server.

Say, panels are all from panelsReader(), how to implement the add/remove button without making an api call (in draft) before clicking the save button?

```javascript
function fetchPanels() {
    return new Promise((resolve) => {
        setTimeout(() => {
            return [
                {name: 'panel_1'},
                {name: 'panel_2'},
            ]
        })
    });
}

function Panels(props) {
    const panels = props.panelsReader();
    function addPanel() {
        // how to add item to panels that avoids api calls or being lost in re-render?
        // some code here...
    }

    function savePanels() { /* ... sync with the server ... */ }
    return (
        <>
            <button onClick={addPanel}>Add Panel</button>
            <button onClick={savePanels}>Save</button>
            {panels.map((panel) => (
                <div>{panel.name}</div>
            ))}
        </>
    )
}

function Dashboard() {
    const [panelsReader, updatePanelsReader] = useAsyncResource(fetchPanels, []);
    return (
        <Suspense fallback="loading...">
            <Panels panelsReader={panelsReader} />
        </Suspense>
    )
}

```

**Comment by andreiduca** [comment]
The `useAsyncResource` hook is mostly for data fetching from the server. If you want to change the data locally, you can keep it in a local state inside your component, initialize it from the data reader, and manipulate it at will. Once you save the data back to the server, you can re-fetch it and update the local state with fresh (and updated) data from the server.

**Comment by ace-han** [comment]
@andreiduca Agreed with that. 

However, I would like to know how to work with `Suspense` if I initialize `this local state` from `data reader`. 

Will `this local state` lose something that `Suspense` requires?

**Comment by andreiduca** [comment]
You would probably want to work with `useState` hooks, since you're using function components. This is not mutually exclusive with the Suspense patterns.
