### ISSUE TITLE
combining with import useErrorHandler of 'react-error-boundary' module

### ISSUE THREAD

**Issue by quertenmont** [andreiduca/use-async-resource#48]
Hello,

is there a recommended way to combine this package with the useErrorHandler of 'react-error-boundary' module ?
It would be nice to provide a handler to catch fetch API errors and handle them with useErrorHandler

That would make the package great to handle both suspense and errorBoundary

thanks for your advices
Loic

**Comment by andreiduca** [comment]
Hi @quertenmont

If your fetch call fails, the wrapping api function will be a rejected Promise which `useAsyncResource` throws inline (so synchronously) and the React Error boundary will catch it. This (I think) makes the use of the `useErrorHandler` hook you mentioned redundant.

You can use the included `AsyncResourceContent` as described here: https://github.com/andreiduca/use-async-resource#default-suspense-and-errorboundary-wrappers
Agree, it can be improved (especially the included error boundary), but try it out and let me know what you think it's missing from it.

It also supports custom error boundary components: https://github.com/andreiduca/use-async-resource#custom-error-boundary
