### ISSUE TITLE
How to reset lazy function

### ISSUE THREAD

**Issue by fmendez89** [andreiduca/use-async-resource#59]
Hi, 
is there a way to reset lazy function?

Say you have this fetcher
```js
const [collectionsReader, getCollections] = useAsyncResource(fetchDataSourceCollections);
```
which fetchDataSourceCollections has one string argument. 

Say you have called ```getCollections(string)``` few times, but you need to reset ```collectionsReader``` to undefined to set inital state of the fetcher. 

Is there a way to reset to the initial state of the lazy function?

**Comment by andreiduca** [comment]
No, it is not possible to "reset" the fetcher. But, depending on your use case, this can be mitigated.

Both the initialization and the updater function create a value in the cache for the given parameters. The data reader is only a means to retrieve that value from the cache. By "resetting" the data reader I imagine you'd want it to not point to any value from the cache anymore?

I think if you had no use for the data reader at some point, maybe you could use a flag (a local state) to not render the component consuming the data reader. I would be curious to learn more about your particular use case, but something like this would probably address your situation:

```jsx
const [userId, setUserId] = useState();
const [userData, getUserDdata] = useAsyncResource(fetchUser);

const selectUser = useCallback((id) => {
  // set a local state, even if undefined
  setUserId(id);

  // however, only get user data for a given existing id
  if (id) {
    getUserDdata(id);
  }
}, []);

return (
  <ul>
    <li><button onClick={() => selectUser(1)}>User id 1<button></li>
    <li><button onClick={() => selectUser(2)}>User id 2<button></li>
    ...
  </ul>
  {userId && (
    <React.Suspense fallback="loading...">
      <UserDetails data={userData} onClose={() => selectUser(undefined)} />
    </React.Suspense>
  )}
);
```

where `UserDetails` could be

```jsx
const userData = props.data();

return (
  <button onClick={props.onClose}>Back</div>

  <div>
    <h1>{userData.fullName}</div>
    ...
  </div>
);
```
